local rrq = bindArg(relative_require, "utils._test.advanced-interfacing")

rrq("alert")
rrq("do-when-ready")
rrq("ipc-socket")
rrq("json")
rrq("prompt")
rrq("query-page")
rrq("run-threaded")
rrq("gpt3")