local rrq = bindArg(relative_require, "utils.specific-domain-ops")


rrq("build-chooser")
rrq("component-interface")
rrq("do-with-temp-file")
rrq("email")
rrq("hotkey-to-string")
rrq("list-with-path")
rrq("log")
rrq("next-cron")
rrq("process-cronlikes")
rrq("process-date-specification")
rrq("quick-path-checks")
rrq("search-engines")
rrq("serve")
rrq("specific-text-stylings")
rrq("stream-play-permutations")
rrq("sync-home-relative-path")
rrq("tags")
rrq("unix-time-last-midnight")
rrq("urlencode")