sipairs = toStatefulGenerator(ipairs)
spairs = toStatefulGenerator(pairs)
skeys = toStatefulGenerator(pairs, 1, 1)
svalues = toStatefulGenerator(pairs, 2, 2)
sikeys = toStatefulGenerator(ipairs, 1, 1)
sivalues = toStatefulGenerator(ipairs, 2, 2)