local rrq = bindArg(relative_require, "items-managers.items")

rrq("array")
rrq("table")
rrq("application")
rrq("string")
rrq("system")
rrq("audiodevice")
rrq("input-method")
rrq("date-and-time")
rrq("running-application")
rrq("contact-table")
rrq("event-table")
rrq("env")
rrq("stream")
rrq("number")
rrq("timer")
rrq("creatable")
rrq("windowlike")
rrq("_test")
