local rrq = bindArg(relative_require, "items-managers.items")

rrq("array")
rrq("table")
rrq("application")
rrq("string")
rrq("system")
rrq("path-leaf-parts")
rrq("audiodevice")
rrq("input-method")
rrq("shell-command")
rrq("date")
rrq("api")
rrq("running-application")
rrq("contact-table")
rrq("event-table")
rrq("env")
rrq("stream")
rrq("number")
rrq("hotkey")
rrq("timer")
rrq("task")
rrq("watcher")
rrq("windowlike")
rrq("_test")
