local rrq = bindArg(relative_require, "items-managers.items.array.non-empty-array.does-not-contain-nil-array.homogeneous-array.array-of-interfaces.managed-array")

rrq("managed-clipboard-array")
rrq("managed-hotkey-array")
rrq("managed-stream-array")
rrq("managed-timer-array")
rrq("managed-api-array")
rrq("managed-input-method-array")
rrq("managed-watcher-array")
rrq("managed-array")