siprs = toStatefulGenerator(iprs)
sikeys = toStatefulGenerator(iprs, 1, 1)
sivalues = toStatefulGenerator(iprs, 2, 2)
sprs = toStatefulGenerator(prs)
skeys = toStatefulGenerator(prs, 1, 1)
svalues = toStatefulGenerator(prs, 2, 2)