siprs = toStatefulGenerator(iprs)
sipairs = toStatefulGenerator(ipairs)
siks = toStatefulGenerator(iprs, 1, 1)
sivls = toStatefulGenerator(iprs, 2, 2)
sprs = toStatefulGenerator(prs)
spairs = toStatefulGenerator(pairs)
sks = toStatefulGenerator(prs, 1, 1)
svls = toStatefulGenerator(prs, 2, 2)