local rrq = bindArg(relative_require, "items-managers.items.string.path.absolute-path.path-existance.extant-path.file.plaintext-file")

rrq("m3u-file")
rrq("executable-code-file")
rrq("plaintext-table-file")
rrq("plaintext-tree-file")
rrq("plaintext-dictionary-file")
rrq("log-file")
rrq("email-file")
rrq("newsboat-urls-file")
rrq("gitignore-file")
rrq("md-file")
rrq("plaintext-file")