g_search_engines = {
  wiktionary = { url = "https://en.wiktionary.org/wiki/%s", short = "wkt", emoji_icon = "⬜️" },
  wikipedia = { url = "https://en.wikipedia.org/wiki/%s", short = "wp", emoji_icon = "🏐" },
  youtube = { url = "https://www.youtube.com/results?search_query=%s", short = "yt", emoji_icon = "🟥▶️" },
  jisho = { url = "https://jisho.org/search/%s", short = "ji", spaces_percent = true, emoji_icon = "🟩" },
  glottopedia = { url = "https://glottopedia.org/index.php?search=", short = "gl", emoji_icon = "🟧" },
  ["ruby-apidoc"] = { url = "https://apidock.com/ruby/search?query=%s", short = "rb", emoji_icon = "🔴" },
  ["python-docs"] = { url = "https://docs.python.org/3/search.html?q=%s", short = "py", emoji_icon = "🐍" },
  ["merriam-webster"] = { url = "https://www.merriam-webster.com/dictionary/%s", short = "mw", emoji_icon = "🆎" },
  ["dict-cc"] = { url = "https://www.dict.cc/?s=%s", short = "dc", emoji_icon = "📙" },
  ["deepl-en-ja"] = { url = "https://www.deepl.com/translator#en/ja/%s", short = "dej", spaces_percent = true, emoji_icon = "🟦🇺🇸🇯🇵" },
  ["deepl-de-en"] = { url = "https://www.deepl.com/translator#de/en/%s", short = "dde", spaces_percent = true, emoji_icon = "🟦🇩🇪🇺🇸" },
  mdn = { url = "https://developer.mozilla.org/en-US/search?q=%s", emoji_icon = "🦊" },
  scihub = { url = "https://sci-hub.st/%s", emoji_icon = "🦅" },
  libgen = { url = "https://libgen.rs/search.php?req=%s", emoji_icon = "⛴" },
  ["semantic-scholar"] = { url = "https://www.semanticscholar.org/search?q=%s", short = "ss", emoji_icon = "👩‍🔧🎓" },
  ["google-scholar"] = { url = "https://scholar.google.com/scholar?q=%s", short = "gs", emoji_icon = "🏳️‍🌈🎓" },
  ["google-images"] = { url = "https://www.google.com/search?tbm=isch&q=%s", short = "gi", emoji_icon = "🏳️‍🌈🖼" },
  ["google-maps"] = { url = "https://www.google.com/maps/search/%s", short = "gm", emoji_icon = "🏳️‍🌈🗺" },
  ["danbooru"] = { url = "https://danbooru.donmai.us/posts?tags=%s", short = "db" },
  ["gelbooru"] = { url = "https://gelbooru.com/index.php?page=post&s=list&tags=%s", short = "gb" },
}