local rrq = bindArg(relative_require, "utils.advanced-interfacing")

rrq("alert")
rrq("do-input")
rrq("do-when-ready")
rrq("do-with-activated")
rrq("function-shell-args")
rrq("gpt3")
rrq("ipc-socket")
rrq("json")
rrq("youtube")
rrq("prompt")
rrq("query-page")
rrq("run-threaded")