local rrq = bindArg(relative_require, "items-managers.items.shell-command")

rrq("khard")
rrq("khal")
rrq("mullvad")
rrq("pass")
rrq("syn")
rrq("synonyms")
rrq("upkg")
rrq("uni")
rrq("libreoffice")
rrq("pandoc")
rrq("shell-command")