local rrq = bindArg(relative_require, "utils._test.type.indexable.general")

rrq("append")
rrq("chunk")
rrq("concat")
rrq("elem-at")
rrq("find")
rrq("findsingle")
rrq("glue")
rrq("len")
rrq("longest-common-prefix")
rrq("multiply")
rrq("replace")
rrq("rev")
rrq("slice")
rrq("sliceable")
rrq("splice")
rrq("split")