local rrq = bindArg(relative_require, "items-managers.items.string-views.item-string-item.single-item-string-item.printable-ascii-string-item")

rrq("doi")
rrq("iban")
rrq("email-address")
rrq("phone-number")
rrq("digit-string")
rrq("num")
rrq("handle")
rrq("date-related")
rrq("dice-notation")
rrq("base-64")
rrq("base-32")
rrq("unicode-codepoint")
rrq("alphanum-minus-underscore")
rrq("printable-ascii-string")